[package]
name = "reactor"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = "0.38.0"
bytemuck = { version = "1.24.0", features = ["derive"] }
env_logger = "0.11.8"
glam = "0.30.9"
gpu-allocator = "0.28.0"
log = "0.4.29"
raw-window-handle = "0.6.2"
winit = "0.30.12"
